#!/bin/bash

user=$( whoami)
uid=$( id -u $user )
processes=$( ps -aux | less )
location=$( pwd )
priv=$( sudo -l | grep \( )

echo -en " This is a snapshot of your current system
  User is: $user
  UID : $uid
  Processes: $processes
  location: $location
  privelages: $priv 
"


~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
~                                                                               
"scriptlab2" 17L, 284C                                        1,1           All
